apiVersion: apps/v1
kind: Deployment 
metadata:
  name: configmap-env-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: configmap-env
  template:
    metadata:
      labels:
        app: configmap-env
    spec:
      containers:
      - name: app-container
        image: nginx:latest
        ports:
        - containerPort: 80
        env:
        - name: APP_MESSAGE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app.message
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: app.port
