apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
  namespace: mysql-lab
data:
  master.cnf: |
    [mysqld]
    server-id=1
    log-bin=mysql-bin
    read-only=0
  replica.cnf: |
    [mysqld]
    server-id=2
    read-only=1
    relay-log=relay-bin
    log-bin=mysql-bin
