apiVersion: v1
kind: Service
metadata:
  name: mysqld
  namespace: mysql-lab
spec:
  selector:
    app: mysql   # target pod with this name
  ports:
  - port: 3306
    name: mysql
  clusterIP: None # this makes it a stateless service
