apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mysql-lab
spec:
  serviceName: mysql
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: mysql
        image: mysql:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3306
          name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: root-password
        - name: MYSQL_REPLICATION_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: replica-user
        - name: MYSQL_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: replica-password
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        command: ["/bin/sh", "-c"]
        args:
          - |
            index=$(echo ${HOSTNAME} | awk -F '-' '{print $2}');
            if [ "$index" = "0" ]; then
              server_id=1;
              read_only=0;
            else
              server_id=$(($index+1));
              read_only=1;
            fi;
            exec mysqld --server-id=$server_id --read-only=$read_only --log-bin=mysql-bin --relay-log=relay-bin
  volumeClaimTemplates:
  - metadata:
      name: mysql-persistent-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 1Gi

