apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: mysql-lab
type: Opaque
data:
  root-password: cGFzc3dvcmQ=  # base64 for "password"
  replica-user: cmVwbGljYV91c2Vy   # base64 for "replica_user"
  replica-password: cmVwbGljYV9wYXNzd29yZA==   # base64 for "replica_password"