apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-volume-deployment
spec:
  selector:
    matchLabels:
      app: secret-volume
  template:
    metadata:
      labels:
        app: secret-volume
    spec:
      containers:
      - name: secret-volume
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret-volume
          readOnly: true
      volumes:
      - name: secret-volume
        secret:
          secretName: db-secret